(add-to-list 'load-path "~/.elisp")
(add-to-list 'load-path "~/.elisp/cedet-1.0pre6/semantic")
(add-to-list 'load-path "~/.elisp/cedet-1.0pre6/eieio")
(add-to-list 'load-path "~/.elisp/cedet-1.0pre6/speedbar")
(add-to-list 'load-path "~/.elisp/ecb-2.32")
;; (add-to-list 'load-path "~/.elisp/ac")

;; (add-to-list 'load-path "~/.elisp/csharp")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/w3m")
(add-to-list 'load-path "/usr/share/emacs/site-lisp")

(load-file "~/.emacs.d/preference/05color.el")
(load-file "~/.emacs.d/preference/05ui.el")
(load-file "~/.emacs.d/preference/10fonts.el")
(load-file "~/.emacs.d/preference/25functions.el")
(load-file "~/.emacs.d/preference/25keybindings.el")
(load-file "~/.emacs.d/preference/25modes.el")
(load-file "~/.emacs.d/preference/25personal.el")
(load-file "~/.emacs.d/preference/50AC.el")
(load-file "~/.emacs.d/preference/50AUCTeX.el")
(load-file "~/.emacs.d/preference/50muse.el")
(load-file "~/.emacs.d/preference/50dired.el")
(load-file "~/.emacs.d/preference/50tabbar.el")
(load-file "~/.emacs.d/preference/50hide.el")
(load-file "~/.emacs.d/preference/50CEDET.el")
(load-file "~/.emacs.d/preference/50yasnippet.el")
;; (load-file "~/.emacs.d/preference/50imaxima.el")
(load-file "~/.emacs.d/preference/50chinese.el")
;; (load-file "~/.emacs.d/preference/50twit.el")
(load-file "~/.emacs.d/preference/50python.el")
(load-file "~/.emacs.d/preference/50misc.el")
(load-file "~/.emacs.d/preference/60cpp.el")
(load-file "~/.emacs.d/preference/60css-mode.el")
;; (load-file "~/.emacs.d/preference/60gnus.el")
;; (load-file "~/.emacs.d/preference/60w3m.el")
;; (load-file "~/.emacs.d/preference/60jabber.el")
(load-file "~/.emacs.d/preference/60git.el")
(load-file "~/.emacs.d/preference/60calendar.el")
;; (load-file "~/.emacs.d/preference/csharp.el")


;; git.el(load-file "/usr/local/share/emacs/site-lisp/dvc/dvc-load.el")
;; (load-file "~/.emacs.d/preference/60weblogger.el")

(server-start)