(setq elisp-home "~/.elisp")
(setq preference-home "~/.emacs.d/preference")

(add-to-list 'load-path elisp-home)
(add-to-list 'load-path "/usr/share/emacs/site-lisp")
(add-to-list 'load-path (concat elisp-home "/magit"))
(add-to-list 'load-path (concat elisp-home "/twittering-mode"))

(load-file (concat preference-home "/05color.el"))
(load-file (concat preference-home "/05ui.el"))
(load-file (concat preference-home "/10fonts.el"))
(load-file (concat preference-home "/25functions.el"))
(load-file (concat preference-home "/25keybindings.el"))
(load-file (concat preference-home "/25modes.el"))
(load-file (concat preference-home "/25personal.el"))
(load-file (concat preference-home "/50AC.el"))
(load-file (concat preference-home "/50AUCTeX.el"))
(load-file (concat preference-home "/50muse.el"))
(load-file (concat preference-home "/50dired.el"))
(load-file (concat preference-home "/50tabbar.el"))
(load-file (concat preference-home "/50hide.el"))
(load-file (concat preference-home "/50CEDET.el"))
(load-file (concat preference-home "/50yasnippet.el"))
;; (load-file (concat preference-home "/50imaxima.el"))
(load-file (concat preference-home "/50chinese.el"))
;; (load-file (concat preference-home "/50twit.el"))
(load-file (concat preference-home "/50python.el"))
(load-file (concat preference-home "/50misc.el"))
(load-file (concat preference-home "/60cpp.el"))
(load-file (concat preference-home "/60css-mode.el"))
;; (load-file (concat preference-home "/60gnus.el"))
;; (load-file (concat preference-home "/60w3m.el"))
;; (load-file (concat preference-home "/60jabber.el"))
(load-file (concat preference-home "/60git.el"))
(load-file (concat preference-home "/60calendar.el"))
;; (load-file (concat preference-home "/csharp.el"))


;; git.el(load-file "/usr/local/share/emacs/site-lisp/dvc/dvc-load.el")
;; (load-file (concat preference-home "/60weblogger.el"))

(server-start)
